/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalexpensetracker;

/**
 *
 * @author KANI
 */
public class expense extends javax.swing.JFrame {

    /**
     * Creates new form expense
     */
    public expense() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlbase = new javax.swing.JPanel();
        btnAddexpense = new javax.swing.JButton();
        btncheckExpense = new javax.swing.JButton();
        btnSetlimit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);

        pnlbase.setBackground(new java.awt.Color(212, 236, 220));

        btnAddexpense.setBackground(new java.awt.Color(212, 236, 220));
        btnAddexpense.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnAddexpense.setText("ADD EXPENSES");
        btnAddexpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddexpenseMouseClicked(evt);
            }
        });
        btnAddexpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddexpenseActionPerformed(evt);
            }
        });

        btncheckExpense.setBackground(new java.awt.Color(212, 236, 220));
        btncheckExpense.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btncheckExpense.setText("CHECK EXPENSES");
        btncheckExpense.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncheckExpenseMouseClicked(evt);
            }
        });

        btnSetlimit.setBackground(new java.awt.Color(212, 236, 220));
        btnSetlimit.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        btnSetlimit.setText("SET LIMIT");
        btnSetlimit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSetlimitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSetlimitMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pnlbaseLayout = new javax.swing.GroupLayout(pnlbase);
        pnlbase.setLayout(pnlbaseLayout);
        pnlbaseLayout.setHorizontalGroup(
            pnlbaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlbaseLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addGroup(pnlbaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddexpense, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncheckExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetlimit, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(202, 202, 202))
        );
        pnlbaseLayout.setVerticalGroup(
            pnlbaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlbaseLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnAddexpense, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btncheckExpense, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnSetlimit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlbase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlbase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddexpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddexpenseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        AddExpense.main(null);
    }//GEN-LAST:event_btnAddexpenseMouseClicked

    private void btnAddexpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddexpenseActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_btnAddexpenseActionPerformed

    private void btncheckExpenseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncheckExpenseMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new CheckExpense().setVisible(true);
    }//GEN-LAST:event_btncheckExpenseMouseClicked

    private void btnSetlimitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetlimitMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetlimitMouseEntered

    private void btnSetlimitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSetlimitMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new SetLimit().setVisible(true);
    }//GEN-LAST:event_btnSetlimitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new expense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddexpense;
    private javax.swing.JButton btnSetlimit;
    private javax.swing.JButton btncheckExpense;
    private javax.swing.JPanel pnlbase;
    // End of variables declaration//GEN-END:variables
}
